### ISSUE TITLE
[Question/Feature request] Adaptation for low memory devices

### ISSUE THREAD

**Issue by jbnjohnathan** [stm32duino/VL53L4CX#12]
I have been using the VL6180X sensor connected to an Arduino Pro Mini which is using a ATmega328P. 
Is there a reason the library for the VL54L4CX need so much memory that it cannot be loaded on to a ATmega328P?
It would be great if this sensor could be used with small memory boards as well as they use very little power.

**Comment by cparata** [comment]
Hello @jbnjohnathan ,
unfortunately, this part number is not ideal for small memory devices because the histogram algorithms used in this driver are really heavy in terms of memory usage. On ATmega328P you can try other part numbers like the VL53L4CD that should use less memory. Another option is to change microcontroller and use for example a Nucleo board that has much more memory than an ATmega328P.
Best Regards,
Carlo

**Comment by jbnjohnathan** [comment]
Thanks for the prompt reply!
I thought the computation was done in chip and the module was only needed for communication with it, so I didn't think there should be much difference between the sensors. But now I know better : )

Unfortunately VL53L4CD cannot measure up to 6 meters which I need.
